apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name:  vault-spc-cluster1 
spec:
  provider: vault
  parameters:
    vaultAddress: http://external-vault:8200
    vaultKubernetesMountPath: cluster1
    roleName: cluster1-ns1-role
    objects: |
      - objectName: "TLS_CRT"
        secretPath: secret/data/keypair 
        secretKey: "tls.crt"
      - objectName: "TLS_KEY"
        secretPath: secret/data/keypair 
        secretKey: "tls.key"
      - objectName: "JKSPASS"
        secretPath: secret/data/keypair 
        secretKey: "jkspass"

