jenkins:
  vaultServer: http://0.0.0.0:8200

app:
  appName: webapp-pod
  saName: default
  image: jweissig/app:0.0.1
  containerName: webapp
  path: /mnt/jksfile

init:
  image: openjdk:11-jdk
  pkcsPath: /mnt/jksfile/keystore.pkcs12
  jksPath: /mnt/jksfile/keystore.jks
  csiVolume: /mnt/secrets-store/
  jksfileVolume: /mnt/jksfile
  spcName: vault-spc-cluster1
  keystore_run: echo starting;sleep 5;openssl pkcs12 -export -inkey $TLS_KEY -in $TLS_CRT -out $keystore_pkcs12 -password pass:$JKSPASS;keytool -importkeystore -noprompt -srckeystore $keystore_pkcs12 -srcstoretype pkcs12 -destkeystore $keystore_jks -storepass $JKSPASS -srcstorepass $JKSPASS;echo done
volumes:
  path: /mnt/jksfile

vault:
  secretsPath: secret/data/keypair
  vaultRole: cluster1-role
  address: http://external-vault:8200
  kubernetesMountPath: cluster1
  policyName: cluster1-policy
  
externalvault:
  name: external-vault
  port: 8200
  protocol: TCP
  ip: 192.168.49.1

Secrets:
  secretName: vault-secret
  Objects:
    tlscrt: 
      name: TLS_CRT                                      # Object/Environment name for secret. 
      key: tls.crt                                      # Key name used for secret in vault.
      path: /mnt/secrets-store/TLS_CRT                   # Mount path for secret.
    tlskey:
      name: TLS_KEY
      key: tls.key
      path: /mnt/secrets-store/TLS_KEY
    password:
      name: JKSPASS
      key: jkspass
      path: /mnt/secrets-store/JKS_PASS
    